sudo: false
language: cpp
compiler:
  - clang++
# - g++

install:
  - if [ "$CXX" = "g++" ]; then export CXXFLAGS="-std=c++14"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXXFLAGS="-std=c++14"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - wget -O boost_1_59_0.tar.bz2 http://sourceforge.net/projects/boost/files/latest/download?source=files && tar xf boost_1_59_0.tar.bz2 && cd boost_1_59_0 && cp ../user-config.jam . && cat user-config.jam && ./bootstrap.sh && ./b2 install --address-model=64 --with-system --with-test --prefix=../boost > /dev/null  && cd ..
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake

env:
  - FLAGS="-DMQTT_NO_TLS=ON"
  - FLAGS="-DMQTT_NO_TLS=OFF"

script:
  - mkdir build && cd build && cmake $FLAGS -DBoost_NO_SYSTEM_PATHS=ON -DBOOST_ROOT=`pwd`/../boost -DBOOST_INCLUDEDIR=`pwd`/../boost/include -DBOOST_LIBRARYDIR=`pwd`/../boost/lib .. && make VERBOSE=1 && ctest -VV
